//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/DbDataLibrary.Models.Entities")]
    public partial class Employee : object
    {
        
        private System.Nullable<System.DateTime> AddOnField;
        
        private System.Collections.Generic.List<DbService.AppLogs> AppLogsField;
        
        private System.Nullable<int> DepartamentField;
        
        private DbService.Department DepartamentNavigationField;
        
        private string EmpNameField;
        
        private string EmpSurnameField;
        
        private int IdField;
        
        private System.Nullable<int> IdAdminField;
        
        private DbService.Admin IdAdminNavigationField;
        
        private string IdEmployeeField;
        
        private System.Collections.Generic.List<DbService.Macro> MacroField;
        
        private string MailField;
        
        private string PhoneField;
        
        private string PositionField;
        
        private System.Collections.Generic.List<DbService.Project> ProjectField;
        
        private System.Nullable<int> TeamField;
        
        private DbService.DevTeam TeamNavigationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AddOn
        {
            get
            {
                return this.AddOnField;
            }
            set
            {
                this.AddOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DbService.AppLogs> AppLogs
        {
            get
            {
                return this.AppLogsField;
            }
            set
            {
                this.AppLogsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Departament
        {
            get
            {
                return this.DepartamentField;
            }
            set
            {
                this.DepartamentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DbService.Department DepartamentNavigation
        {
            get
            {
                return this.DepartamentNavigationField;
            }
            set
            {
                this.DepartamentNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpName
        {
            get
            {
                return this.EmpNameField;
            }
            set
            {
                this.EmpNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpSurname
        {
            get
            {
                return this.EmpSurnameField;
            }
            set
            {
                this.EmpSurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdAdmin
        {
            get
            {
                return this.IdAdminField;
            }
            set
            {
                this.IdAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DbService.Admin IdAdminNavigation
        {
            get
            {
                return this.IdAdminNavigationField;
            }
            set
            {
                this.IdAdminNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEmployee
        {
            get
            {
                return this.IdEmployeeField;
            }
            set
            {
                this.IdEmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DbService.Macro> Macro
        {
            get
            {
                return this.MacroField;
            }
            set
            {
                this.MacroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail
        {
            get
            {
                return this.MailField;
            }
            set
            {
                this.MailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DbService.Project> Project
        {
            get
            {
                return this.ProjectField;
            }
            set
            {
                this.ProjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Team
        {
            get
            {
                return this.TeamField;
            }
            set
            {
                this.TeamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DbService.DevTeam TeamNavigation
        {
            get
            {
                return this.TeamNavigationField;
            }
            set
            {
                this.TeamNavigationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/DbDataLibrary.Models.Entities")]
    public partial class Department : object
    {
        
        private System.Nullable<System.DateTime> AddOnField;
        
        private string DepNameField;
        
        private System.Collections.Generic.List<DbService.DevTeam> DevTeamField;
        
        private System.Collections.Generic.List<DbService.Employee> EmployeeField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AddOn
        {
            get
            {
                return this.AddOnField;
            }
            set
            {
                this.AddOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepName
        {
            get
            {
                return this.DepNameField;
            }
            set
            {
                this.DepNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DbService.DevTeam> DevTeam
        {
            get
            {
                return this.DevTeamField;
            }
            set
            {
                this.DevTeamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DbService.Employee> Employee
        {
            get
            {
                return this.EmployeeField;
            }
            set
            {
                this.EmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/DbDataLibrary.Models.Entities")]
    public partial class Admin : object
    {
        
        private System.Nullable<System.DateTime> AddOnField;
        
        private System.Collections.Generic.List<DbService.Employee> EmployeeField;
        
        private int IdField;
        
        private System.Nullable<bool> IsActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AddOn
        {
            get
            {
                return this.AddOnField;
            }
            set
            {
                this.AddOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DbService.Employee> Employee
        {
            get
            {
                return this.EmployeeField;
            }
            set
            {
                this.EmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DevTeam", Namespace="http://schemas.datacontract.org/2004/07/DbDataLibrary.Models.Entities")]
    public partial class DevTeam : object
    {
        
        private System.Nullable<System.DateTime> AddOnField;
        
        private System.Nullable<int> DepartamentField;
        
        private DbService.Department DepartamentNavigationField;
        
        private System.Collections.Generic.List<DbService.Employee> EmployeeField;
        
        private int IdField;
        
        private string MailField;
        
        private string ManagerField;
        
        private System.Collections.Generic.List<DbService.Project> ProjectField;
        
        private string TeamNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AddOn
        {
            get
            {
                return this.AddOnField;
            }
            set
            {
                this.AddOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Departament
        {
            get
            {
                return this.DepartamentField;
            }
            set
            {
                this.DepartamentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DbService.Department DepartamentNavigation
        {
            get
            {
                return this.DepartamentNavigationField;
            }
            set
            {
                this.DepartamentNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DbService.Employee> Employee
        {
            get
            {
                return this.EmployeeField;
            }
            set
            {
                this.EmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail
        {
            get
            {
                return this.MailField;
            }
            set
            {
                this.MailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manager
        {
            get
            {
                return this.ManagerField;
            }
            set
            {
                this.ManagerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DbService.Project> Project
        {
            get
            {
                return this.ProjectField;
            }
            set
            {
                this.ProjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamName
        {
            get
            {
                return this.TeamNameField;
            }
            set
            {
                this.TeamNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppLogs", Namespace="http://schemas.datacontract.org/2004/07/DbDataLibrary.Models.Entities")]
    public partial class AppLogs : object
    {
        
        private System.Nullable<System.DateTime> AddOnField;
        
        private int IdField;
        
        private System.Nullable<int> IdUserField;
        
        private DbService.Employee IdUserNavigationField;
        
        private string LogDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AddOn
        {
            get
            {
                return this.AddOnField;
            }
            set
            {
                this.AddOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdUser
        {
            get
            {
                return this.IdUserField;
            }
            set
            {
                this.IdUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DbService.Employee IdUserNavigation
        {
            get
            {
                return this.IdUserNavigationField;
            }
            set
            {
                this.IdUserNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogDesc
        {
            get
            {
                return this.LogDescField;
            }
            set
            {
                this.LogDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Macro", Namespace="http://schemas.datacontract.org/2004/07/DbDataLibrary.Models.Entities")]
    public partial class Macro : object
    {
        
        private System.Nullable<System.DateTime> AddOnField;
        
        private string BusinessTeamField;
        
        private string DescriptionField;
        
        private string GmasMacroIdField;
        
        private string GmasMacroWebPageField;
        
        private int IdField;
        
        private System.Nullable<int> MacroDeveloperField;
        
        private DbService.Employee MacroDeveloperNavigationField;
        
        private string MacroNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AddOn
        {
            get
            {
                return this.AddOnField;
            }
            set
            {
                this.AddOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessTeam
        {
            get
            {
                return this.BusinessTeamField;
            }
            set
            {
                this.BusinessTeamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GmasMacroId
        {
            get
            {
                return this.GmasMacroIdField;
            }
            set
            {
                this.GmasMacroIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GmasMacroWebPage
        {
            get
            {
                return this.GmasMacroWebPageField;
            }
            set
            {
                this.GmasMacroWebPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MacroDeveloper
        {
            get
            {
                return this.MacroDeveloperField;
            }
            set
            {
                this.MacroDeveloperField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DbService.Employee MacroDeveloperNavigation
        {
            get
            {
                return this.MacroDeveloperNavigationField;
            }
            set
            {
                this.MacroDeveloperNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MacroName
        {
            get
            {
                return this.MacroNameField;
            }
            set
            {
                this.MacroNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/DbDataLibrary.Models.Entities")]
    public partial class Project : object
    {
        
        private string BenefitsField;
        
        private string CommentField;
        
        private string ContactPersonField;
        
        private string DevCommentField;
        
        private System.Nullable<int> DevTeamField;
        
        private DbService.DevTeam DevTeamNavigationField;
        
        private System.Nullable<int> DeveloperField;
        
        private DbService.Employee DeveloperNavigationField;
        
        private System.Nullable<System.DateTime> DueDateField;
        
        private System.Nullable<float> FteSavingsField;
        
        private int IdField;
        
        private string MacroNameField;
        
        private string PiorityField;
        
        private DbService.ProjectPriority PiorityNavigationField;
        
        private string ProjectNameField;
        
        private string ProjectStatusField;
        
        private DbService.ProjectStatus ProjectStatusNavigationField;
        
        private string ProjectTypeField;
        
        private DbService.ProjectType ProjectTypeNavigationField;
        
        private string RequestingTeamField;
        
        private System.Nullable<System.DateTime> SubmitionTimeField;
        
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Benefits
        {
            get
            {
                return this.BenefitsField;
            }
            set
            {
                this.BenefitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPerson
        {
            get
            {
                return this.ContactPersonField;
            }
            set
            {
                this.ContactPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevComment
        {
            get
            {
                return this.DevCommentField;
            }
            set
            {
                this.DevCommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DevTeam
        {
            get
            {
                return this.DevTeamField;
            }
            set
            {
                this.DevTeamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DbService.DevTeam DevTeamNavigation
        {
            get
            {
                return this.DevTeamNavigationField;
            }
            set
            {
                this.DevTeamNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Developer
        {
            get
            {
                return this.DeveloperField;
            }
            set
            {
                this.DeveloperField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DbService.Employee DeveloperNavigation
        {
            get
            {
                return this.DeveloperNavigationField;
            }
            set
            {
                this.DeveloperNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> FteSavings
        {
            get
            {
                return this.FteSavingsField;
            }
            set
            {
                this.FteSavingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MacroName
        {
            get
            {
                return this.MacroNameField;
            }
            set
            {
                this.MacroNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Piority
        {
            get
            {
                return this.PiorityField;
            }
            set
            {
                this.PiorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DbService.ProjectPriority PiorityNavigation
        {
            get
            {
                return this.PiorityNavigationField;
            }
            set
            {
                this.PiorityNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName
        {
            get
            {
                return this.ProjectNameField;
            }
            set
            {
                this.ProjectNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectStatus
        {
            get
            {
                return this.ProjectStatusField;
            }
            set
            {
                this.ProjectStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DbService.ProjectStatus ProjectStatusNavigation
        {
            get
            {
                return this.ProjectStatusNavigationField;
            }
            set
            {
                this.ProjectStatusNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectType
        {
            get
            {
                return this.ProjectTypeField;
            }
            set
            {
                this.ProjectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DbService.ProjectType ProjectTypeNavigation
        {
            get
            {
                return this.ProjectTypeNavigationField;
            }
            set
            {
                this.ProjectTypeNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestingTeam
        {
            get
            {
                return this.RequestingTeamField;
            }
            set
            {
                this.RequestingTeamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SubmitionTime
        {
            get
            {
                return this.SubmitionTimeField;
            }
            set
            {
                this.SubmitionTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime
        {
            get
            {
                return this.UpdateTimeField;
            }
            set
            {
                this.UpdateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectPriority", Namespace="http://schemas.datacontract.org/2004/07/DbDataLibrary.Models.Entities")]
    public partial class ProjectPriority : object
    {
        
        private string DescriptionField;
        
        private string PriorityNameField;
        
        private System.Collections.Generic.List<DbService.Project> ProjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriorityName
        {
            get
            {
                return this.PriorityNameField;
            }
            set
            {
                this.PriorityNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DbService.Project> Project
        {
            get
            {
                return this.ProjectField;
            }
            set
            {
                this.ProjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectStatus", Namespace="http://schemas.datacontract.org/2004/07/DbDataLibrary.Models.Entities")]
    public partial class ProjectStatus : object
    {
        
        private System.Nullable<System.DateTime> AddOnField;
        
        private string DescriptionField;
        
        private System.Collections.Generic.List<DbService.Project> ProjectField;
        
        private string ProjectStatusNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AddOn
        {
            get
            {
                return this.AddOnField;
            }
            set
            {
                this.AddOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DbService.Project> Project
        {
            get
            {
                return this.ProjectField;
            }
            set
            {
                this.ProjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectStatusName
        {
            get
            {
                return this.ProjectStatusNameField;
            }
            set
            {
                this.ProjectStatusNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectType", Namespace="http://schemas.datacontract.org/2004/07/DbDataLibrary.Models.Entities")]
    public partial class ProjectType : object
    {
        
        private System.Nullable<System.DateTime> AddOnField;
        
        private string DescriptionField;
        
        private System.Collections.Generic.List<DbService.Project> ProjectField;
        
        private string ProjectTypeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AddOn
        {
            get
            {
                return this.AddOnField;
            }
            set
            {
                this.AddOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DbService.Project> Project
        {
            get
            {
                return this.ProjectField;
            }
            set
            {
                this.ProjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectTypeName
        {
            get
            {
                return this.ProjectTypeNameField;
            }
            set
            {
                this.ProjectTypeNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DbService.IOneTrackerDbService")]
    public interface IOneTrackerDbService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneTrackerDbService/GetData", ReplyAction="http://tempuri.org/IOneTrackerDbService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneTrackerDbService/GetData", ReplyAction="http://tempuri.org/IOneTrackerDbService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneTrackerDbService/DataBaseExists", ReplyAction="http://tempuri.org/IOneTrackerDbService/DataBaseExistsResponse")]
        bool DataBaseExists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneTrackerDbService/DataBaseExists", ReplyAction="http://tempuri.org/IOneTrackerDbService/DataBaseExistsResponse")]
        System.Threading.Tasks.Task<bool> DataBaseExistsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneTrackerDbService/GetAllEmployeeRecords", ReplyAction="http://tempuri.org/IOneTrackerDbService/GetAllEmployeeRecordsResponse")]
        System.Collections.Generic.List<DbService.Employee> GetAllEmployeeRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneTrackerDbService/GetAllEmployeeRecords", ReplyAction="http://tempuri.org/IOneTrackerDbService/GetAllEmployeeRecordsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DbService.Employee>> GetAllEmployeeRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneTrackerDbService/GetAllDevTeamsRecords", ReplyAction="http://tempuri.org/IOneTrackerDbService/GetAllDevTeamsRecordsResponse")]
        System.Collections.Generic.List<DbService.DevTeam> GetAllDevTeamsRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneTrackerDbService/GetAllDevTeamsRecords", ReplyAction="http://tempuri.org/IOneTrackerDbService/GetAllDevTeamsRecordsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DbService.DevTeam>> GetAllDevTeamsRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneTrackerDbService/GetAllDepartmentsRecords", ReplyAction="http://tempuri.org/IOneTrackerDbService/GetAllDepartmentsRecordsResponse")]
        System.Collections.Generic.List<DbService.Department> GetAllDepartmentsRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneTrackerDbService/GetAllDepartmentsRecords", ReplyAction="http://tempuri.org/IOneTrackerDbService/GetAllDepartmentsRecordsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DbService.Department>> GetAllDepartmentsRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneTrackerDbService/UserInDB", ReplyAction="http://tempuri.org/IOneTrackerDbService/UserInDBResponse")]
        bool UserInDB(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOneTrackerDbService/UserInDB", ReplyAction="http://tempuri.org/IOneTrackerDbService/UserInDBResponse")]
        System.Threading.Tasks.Task<bool> UserInDBAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IOneTrackerDbServiceChannel : DbService.IOneTrackerDbService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class OneTrackerDbServiceClient : System.ServiceModel.ClientBase<DbService.IOneTrackerDbService>, DbService.IOneTrackerDbService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OneTrackerDbServiceClient() : 
                base(OneTrackerDbServiceClient.GetDefaultBinding(), OneTrackerDbServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOneTrackerDbService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OneTrackerDbServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OneTrackerDbServiceClient.GetBindingForEndpoint(endpointConfiguration), OneTrackerDbServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OneTrackerDbServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OneTrackerDbServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OneTrackerDbServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OneTrackerDbServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OneTrackerDbServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public bool DataBaseExists()
        {
            return base.Channel.DataBaseExists();
        }
        
        public System.Threading.Tasks.Task<bool> DataBaseExistsAsync()
        {
            return base.Channel.DataBaseExistsAsync();
        }
        
        public System.Collections.Generic.List<DbService.Employee> GetAllEmployeeRecords()
        {
            return base.Channel.GetAllEmployeeRecords();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DbService.Employee>> GetAllEmployeeRecordsAsync()
        {
            return base.Channel.GetAllEmployeeRecordsAsync();
        }
        
        public System.Collections.Generic.List<DbService.DevTeam> GetAllDevTeamsRecords()
        {
            return base.Channel.GetAllDevTeamsRecords();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DbService.DevTeam>> GetAllDevTeamsRecordsAsync()
        {
            return base.Channel.GetAllDevTeamsRecordsAsync();
        }
        
        public System.Collections.Generic.List<DbService.Department> GetAllDepartmentsRecords()
        {
            return base.Channel.GetAllDepartmentsRecords();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DbService.Department>> GetAllDepartmentsRecordsAsync()
        {
            return base.Channel.GetAllDepartmentsRecordsAsync();
        }
        
        public bool UserInDB(int id)
        {
            return base.Channel.UserInDB(id);
        }
        
        public System.Threading.Tasks.Task<bool> UserInDBAsync(int id)
        {
            return base.Channel.UserInDBAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOneTrackerDbService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOneTrackerDbService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53311/OneTrackerDbService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OneTrackerDbServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOneTrackerDbService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OneTrackerDbServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOneTrackerDbService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IOneTrackerDbService,
        }
    }
}
